### PR TITLE
Improve performance of validation for database imports

### PR DESCRIPTION
**Pull request by joe-crawford**
- Shallow validate populated collections instead of deep validating imported model
- Save model in importer and set providerHasSavedModels flag

### CODE REVIEW

**Review by jamesrwelch — COMMENTED** [review]
In `validateImportedDataModels` we're now validating the items, and the metadata for each item.  Should we validate other facets too - even if we're not currently populating them?

**Comment by joe-crawford** [comment]
Yes, I could update to validate all the current facets in case we import those in the future too.

**Comment by joe-crawford** [comment]
@jamesrwelch, I've updated to shallow validate the DataModel associations that could be populated in the future, as well as all the facets.

**Comment by joe-crawford** [comment]
When this PR is merged, I'll re-run the 4 database plugin PRs in Jenkins which have some relevant updates to the tests and should pass, except for an existing issue with the Oracle importer.

**Review by jamesrwelch — APPROVED** [review]
Yes, lovely stuff - I really like the generic approach!

**Pull request merged**
